# encoding: UTF-8
namespace :procedure do
  desc "Populate Values for Procedure"
  task :populate => :environment do
    Procedure.delete_all

    procedure = Procedure.create( name: "Entrega de Documentos Necessários à Primeira Habilitação", description: "Entrega de Documentos Necessários à Primeira Habilitação")

    procedure.rules.new(description: "<span class='sbvr yellow'>É permitido que o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>inicie</span> <span class='sbvr yellow'>o</span> <span class='sbvr red'>processo</span> <span class='sbvr yellow'>se, e somente se, o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>seja maior que 18 anos</span>, <span class='sbvr yellow'>o <span class='sbvr red'>candidato</span> <span class='sbvr blue'>saiba ler e escrever, <span class='sbvr yellow'>o <span class='sbvr red'>candidato</span> possua documento de identificação, <span class='sbvr yellow'>e o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr red'>CPF</span>")
    procedure.rules.new(description: "<span class='sbvr yellow'>É permitido que o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>inicie</span> <span class='sbvr yellow'> o</span> <span class='sbvr red'>processo</span> <span class='sbvr yellow'>se, e somente se, o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr yellow'>a</span> <span class='sbvr red'>documentação necessária</span> <span class='sbvr yellow'> e o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>agende</span> <span class='sbvr yellow'>a</span> <span class='sbvr red'>entrega da documentação em um dos postos</span>")
    procedure.rules.new(description: "<span class='sbvr yellow'>É permitido que o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr yellow'>a<span> <span class='sbvr red'>documentação necessária</span> <span class='sbvr yellow'>se, e somente se, o</span> <span class='sbvr red'>candidato</span> <span class='sbvr'>possua</span> <span class='sbvr red'>original do comprovante de residência</span> <span class='sbvr yellow'>e</span> <span class='sbvr red'>cópia do comprovante de residência</span> <span class='sbvr yellow'>e o</span> <span class='sbvr red'>comprovante de residência</span> <span class='sbvr blue'>seja válido</span>")
    procedure.rules.new(description: "<span class='sbvr yellow'>É permitido que o</span> <span class='sbvr red'>comprovante de residência</span> <span class='sbvr blue'>seja válido</span> <span class='sbvr yellow'>se, e somente se, o</span> <span class='sbvr red'>comprovante de residência</span> <span class='sbvr blue'>esteja no nome do</span> <span class='sbvr red'>candidato</span> <span class='sbvr yellow'>ou o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>comprove parentesco com</span> <span class='sbvr red'>titular</span> <span class='sbvr yellow'>do</span> <span class='sbvr red'>comprovante de residência</span> <span class='sbvr yellow'>ou o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>comprove residir com terceiros</span>")
    procedure.rules.new(description: "<span class='sbvr yellow'>É permitido que o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>comprove parentesco com</span> <span class='sbvr yellow'>o</span> <span class='sbvr red'>titular do comprovante de residência</span> <span class='sbvr yellow'>se, e somente se, o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr yellow'>o</span> <span class='sbvr red'>documento de identificação</span> <span class='sbvr yellow'>e o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr yellow'>a</span> <span class='sbvr red'>certidão de nascimento</span> <span class='sbvr yellow'>e o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr yellow'>o</span> <span class='sbvr red'>documento que comprove a união estável</span>")
    procedure.rules.new(description: "<span class='sbvr yellow'>É permitido que o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>comprove residir com terceiros</span> <span class='sbvr yellow'>se, e somente se, o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr yellow'>o</span> <span class='sbvr red'>Formulário Detran/RJ J no.0034</span> <span class='sbvr yellow'>e o</span> <span class='sbvr red'>Formulário Detran/RJ J no.0034</span> <span class='sbvr yellow'>e o</span> <span class='sbvr blue'>esteja assinado pelo</span> <span class='sbvr red'>titular</span> <span class='sbvr yellow'>do</span> <span class='sbvr red'>comprovante de residência</span>")
    procedure.rules.new(description: "<span class='sbvr yellow'>É permitido que o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr yellow'>a</span> <span class='sbvr red'>documentação necessária</span> <span class='sbvr yellow'>se, e somente se, o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr yellow'>o</span> <span class='sbvr red'>original do CPF e cópia do CPF.</span>")
    procedure.rules.new(description: "<span class='sbvr yellow'>É permitido que o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr yellow'>a</span> <span class='sbvr red'>documentação necessária</span> <span class='sbvr yellow'>se o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr red'>original do documento de identificação</span> <span class='sbvr yellow'>e</span> <span class='sbvr red'>cópia do documento de identificação</span>")
    procedure.rules.new(description: "<span class='sbvr yellow'>É permitido que o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr yellow'>a</span> <span class='sbvr red'>documentação necessária</span> <span class='sbvr yellow'>se o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr yellow'>o</span> <span class='sbvr red'>Duda (cod:201-1)</span> <span class='sbvr blue'>pago</span>")
    procedure.rules.new(description: "<span class='sbvr yellow'>É permitido que o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>possua</span> <span class='sbvr yellow'>o</span> <span class='sbvr red'>Duda (cod:201-1)</span> <span class='sbvr blue'>pago</span> <span class='sbvr yellow'>se, e somente e, o</span> <span class='sbvr red'>candidato</span> <span class='sbvr blue'>pagou</span> <span class='sbvr yellow'>o</span> <span class='sbvr red'>Duda (cod: 201-1)</span>")

    procedure.save
  end
end
